### ISSUE TITLE
Missing github organizations

### ISSUE THREAD

**Issue by d4l3k** [ubcfoss/ubc-orgs#1]
Noticed you were missing a few clubs that I'm part of

UBC computer science student society https://github.com/ubccsss

Startup Storm https://github.com/startupstorm

nwHacks https://github.com/nwhacks

**Comment by dohliam** [comment]
Great! Do you want to submit a PR for these? Otherwise I can add them in.

By the way, is nwHacks held/based at UBC? Just want to make sure that the organizations listed have some sort of connection to campus :smile:

**Comment by d4l3k** [comment]
Yeah. Nwhacks is organized by startup storm which is an ams club.

https://www.nwhacks.io

**Comment by d4l3k** [comment]
As for the PR, whatever's easiest for you. Not currently at a computer
hence why I submitted an issue first.

**Comment by dohliam** [comment]
Perfect, I'll add them in! Thanks for the suggestions. Oh and feel free to drop by [our slack channel](https://ubcfoss.slack.com/), where there has been some discussion of organizing some kind of hack night or meetup in the near future!

**Comment by d4l3k** [comment]
Cool. Will do
