### ISSUE TITLE
Don't have push access

### ISSUE THREAD

**Issue by bchugg** [ubcfoss/ubc-orgs#2]
I'd like to add a description to Code the Change, but I can't push to the repo in order to make a pull request. Perhaps members can be given write access to repos, with the `master` branch being protected?

**Comment by dohliam** [comment]
Thanks, that sounds like it could be a good idea! I can look into changing the default permissions for members as suggested (@darshandsoni, what do you think?), but in the meantime, have you tried cloning the repo, making changes to your version, and then submitting a PR from there? This should work for anyone without needing push access.

**Comment by darshandsoni** [comment]
Thanks for the contrib @bchugg! The existing permissions for pushing are typical of most github projects in that everyone can clone their own version of the repo and submit a PR - that would be the recommended way of adding material. But given that it is a collaborative list of things, and not a repository that requires extensive building / testing, it might not be a bad idea to open it out to members of the group. I can certainly understand not wanting to clone an entire repo to add a simple line in.

We shall look into implemented this, in the meantime, perhaps try a clone and PR? Let me know if you have any issues with that though :)

**Comment by bchugg** [comment]
Sweet, will fork and submit a PR. Thanks!
